# Generated by Django 5.0.7 on 2024-08-05 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
